
apiVersion: v1
kind: PersistentVolume                
metadata:
  name: cast-pv             
spec:
  capacity:
    storage: 1Gi                                              
  accessModes:
    - ReadWriteOnce                                            
  hostPath:
    path: "/var/lib/rancher/k3s/storage/cast"                       
  storageClassName: ""              


---

apiVersion: v1
kind: PersistentVolumeClaim             
metadata:
  name: pvc-cast             
spec:
  accessModes:
    - ReadWriteOnce                                                    
  storageClassName: ""
  volumeName: cast-pv                               
  resources:
    requests:
      storage: 128Mi


---

apiVersion: v1
kind: Service
metadata:
  name: castdb       
spec:                      
  selector:               
    app: castdb  
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP        
    port: 5432              
    targetPort: 5432        
  type: ClusterIP         

                                     

---

apiVersion: apps/v1                            
kind: StatefulSet                                    
metadata:                                            
  name: castdb                                     
spec:
  serviceName: castdb                                   
  replicas: 1                                 
  selector:                                        
    matchLabels:                                    
      app: castdb                                 
  template:                                        
    metadata: 
      labels:
        app: castdb                              
    spec:                                          
      volumes:                                       
        - name: castdb                        
          persistentVolumeClaim:
            claimName: pvc-cast                
      containers:
        - name: castdb                             
          image: postgres:12.1-alpine
          ports:
            - containerPort: 5432                    
          volumeMounts:                              
            - mountPath: "/var/lib/postgresql/data"    
              name: castdb                     
          env:                                      
            - name: POSTGRES_USER
              value: cast_db_username
            - name: POSTGRES_PASSWORD
              value: cast_db_password
            - name: POSTGRES_DB                     
              value: cast_db_dev
                    
