apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.castStatefulSet.name }}
spec:
  serviceName: {{ .Values.castStatefulSet.serviceName }}
  replicas: {{ .Values.castStatefulSet.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.castStatefulSet.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.castStatefulSet.labels.app }}
    spec:
      volumes:
        - name: {{ .Values.castStatefulSet.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.castStatefulSet.volume.claimName }}
      containers:
        - name: {{ .Values.castStatefulSet.container.name }}
          image: {{ .Values.castStatefulSet.container.image }}
          ports:
            - containerPort: {{ .Values.castStatefulSet.container.port }}
          volumeMounts:
            - mountPath: {{ .Values.castStatefulSet.container.mountPath }}
              name: {{ .Values.castStatefulSet.volume.name }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.castStatefulSet.container.env.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.castStatefulSet.container.env.POSTGRES_PASSWORD }}
            - name: POSTGRES_DB
              value: {{ .Values.castStatefulSet.container.env.POSTGRES_DB }}
